[build-system]
requires = ["setuptools>=0.46", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "dsgtools/_version.py"

[tool.isort]
profile = "black"
